name: TurkceFactions
version: 1.0
main: com.samet.turkcefactions.Klan
api-version: 1.20
softdepend: [Floodgate]
commands:
  klan:
    description: Bedrock Klan Menusu
    usage: /klan
  arsa:
    description: 64x64 Satilik Arsa Menusu
    usage: /arsa
  kit:
    description: Kit Menusu
    usage: /kit
  kc:
    description: Klan Sohbeti
    usage: /kc <mesaj>
